


apiVersion: batch/v1
kind: Job
metadata:
  name: install-vault
  namespace: glowing-tribble
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000

      volumes:
        - name: install-vault-values-source
          hostPath:
            path: /tmp/generic/file%3A/helm
            type: Directory

        - name: install-vault-chart-source
          hostPath:
            path: /tmp/helm/https%3A%2F%2Fhelm.releases.hashicorp.com/vault_0.23.0
            type: Directory

            

        - name: script
          configMap:
            name: install-vault-cm
            defaultMode: 0110
          
      containers:
      - name: install-vault

        image: rancher/klipper-helm:v0.7.4-build20221121
        command: [ "/bin/bash", "-c" ]
        args: [ "/opt/script.sh" ]
        # args: [ "sleep 10000" ]
        imagePullPolicy: Never
        env:
        - name: DEST_REGISTRY_HOST
          value: "registry-insecure"
        - name: DEST_REGISTRY_PORT
          value: "5000"
        volumeMounts:
        - name: install-vault-values-source
          mountPath: /var/lib/values
        - name: install-vault-chart-source
          mountPath: /var/lib/charts
        - name: script
          mountPath: /opt/script.sh
          subPath: script.sh

      restartPolicy: Never

  backoffLimit: 14