apiVersion: batch/v1
kind: Job
metadata:
  name: skopeo
  namespace: glowing-tribble
spec:
  template:
    spec:
      volumes:
        - name: skopeo-source
          hostPath:
            path: /tmp/docker
            type: Directory

        - name: script
          configMap:
            name: skopeo-cm

      containers:
      - name: skopeo
        image: registry1.dso.mil/ironbank/opensource/containers/skopeo:latest
        command: [ "/bin/bash", "-c", "/opt/script.sh" ]
        imagePullPolicy: Never
        volumeMounts:
        - name: skopeo-source
          mountPath: /home/skopeo/source
          readOnly: true
        - name: script
          mountPath: /opt/script.sh
      restartPolicy: Never

  backoffLimit: 14
