apiVersion: batch/v1
kind: Job
metadata:
  name: skopeo
spec:
  template:
    spec:
      containers:
      - name: skopeo
        image: registry1.dso.mil/ironbank/opensource/containers/skopeo:latest
        command: ["--help"]
      restartPolicy: Never
  backoffLimit: 4