
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: glowing-tribble
  name: utility
  labels:
    app: utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
      - name: utility
        image: localhost/utility:latest
        imagePullPolicy: Never
