schemaVersion: v1
kind: authentication
metadata:
    name: Registry1Credentials
    version: v1
    description: d1
credential_required_services:
    - url: https://registry1.dso.mil
      user: ${REG1_USERNAME}
      pass_env: REG1_PASSWORD