---
schemaVersion: v1
kind: manifest

metadata:
  name: "My First Manifest"
  version: 0.1.0
  description: "An introductory manifest"

sboms:
  - local: sbom.json
  - local: sbom-vault.json

includes: []

repositories:
  generic:
  - url: "file:"

  docker:
  - url: https://registry1.dso.mil
  - url: https://docker.io
  - url: https://quay.io

  helm:
  - url: https://helm.releases.hashicorp.com/
